### ISSUE TITLE
Error Message: Value cannot be null. Parameter name: uriString

### ISSUE THREAD

**Issue by MOe2377** [SAP-samples/data-warehouse-cloud-connectors#17]
Hello Olaf, 

We have configured according to the latest documentation, but still receive an error message during login attempt.

I would really appreciate if you could have a look on this. 

Kind Regards,

Mustafa

Here is also the paragraph from the content of the trace file.

Feedback Type:
Frown (Error)
 
Error Message:
Value cannot be null.
Parameter name: uriString
 
Stack Trace:
System.ArgumentNullException
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at System.UriBuilder..ctor(String uri)
   at Microsoft.Mashup.Client.UI.Extensions.Windows.SystemBrowserOAuthDialog.WrapUrlForPowerBiOAuthRedirect(Uri authorizationUri, UriBuilder redirectUriBuilder)
   at Microsoft.Mashup.Client.UI.Extensions.Windows.SystemBrowserOAuthDialog.Authorize(Uri logoutUri, Uri authorizationUri)
   at Microsoft.Mashup.Client.UI.Shared.OAuthManager.OpenOAuthDialog(IWindowHandle parentWindowHandle, ITelemetryService telemetryService, String resourceKind, String accessToken, String resourceUrl)
   at Microsoft.Mashup.Client.UI.Shared.OAuthManager.<>c__DisplayClass6_0.<OpenOAuthDialog>b__0()
   at Microsoft.Mashup.Client.UI.Shared.OAuthManager.<>c__DisplayClass7_0.<AsyncGetOAuthResult>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
 
Stack Trace Message:
Value cannot be null.
Parameter name: uriString

![image](https://github.com/SAP-samples/data-warehouse-cloud-connectors/assets/127397333/93d5e3dd-633b-436c-9256-46dd5a9f4d97)

![image](https://github.com/SAP-samples/data-warehouse-cloud-connectors/assets/127397333/d2253553-75f6-47f8-9f77-71658e5ec630)

**Comment by OlafFischer** [comment]
Hi MOe2377, 
could you please provide additional details of steps you are performing? At which point of time or after which step the error occurs?
Thanks a lot, Olaf

**Comment by MOe2377** [comment]
Hello Olaf,
Thank you for the provided direct-support. It was very much appreciated.

As discussed, we switched off Default Browser, afterwards we were able to connected and authenticate.

Kind Regards, 

Mustafa


<img width="497" alt="Bild (3)" src="https://github.com/SAP-samples/data-warehouse-cloud-connectors/assets/127397333/083f9b1a-dfb8-4df9-a8fa-257f0a6ad0e0">

**Comment by alexduch22** [comment]
I have the same problem with the error message "Value cannot be null. Parameter name: uriString".
When I switch off the "Use my default web browser", I no longer have the problem but I still cannot connect. It seems the logon scren opens and closes immediately without letting me enter my credentials. Could you help me solve this?
Thanks,
Alex

**Comment by gustavokath** [comment]
Closing due to inactivity
